# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 5

environment:
  matrix:
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: true


cache:
  - 'node_modules -> package.json'